### ISSUE TITLE
Error when init

### ISSUE THREAD

**Issue by gridworkz** [smartinsantos/sherman#16]
I get the following error towards the end of `bin/init`

....
app-mysql    | 2020-11-01T17:07:07.022650Z 0 [Warning] 'user' entry 'root@app-mysql' ignored in --skip-name-resolve mode.
app-mysql    | 2020-11-01T17:07:07.055617Z 0 [Note] Event Scheduler: Loaded 0 events
app-mysql    | 2020-11-01T17:07:07.056001Z 0 [Note] mysqld: ready for connections.
app-mysql    | Version: '5.7.32'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
app-go_1     | failed to build, error: exit status 1
....

I check `netstat -tulpn` and I notice 3306 isn't present.

EDIT: Update, I cleaned out docker, re-installed and did `bin/up` and it's working. Is there anything I should be seeing in the browser?

**Comment by smartinsantos** [comment]
Hey @gridworkz you shouldn’t if you are using the defaults the app should be running on port 5000 you will have the endpoints described on https://github.com/smartinsantos/sherman/blob/master/src/app/router/router.go 

at your disposal at localhost:5000/ap1/v1/<route_name>

You could create a ping route though at / and see the response in the browser

**Comment by gridworkz** [comment]
Cool, thanks.
